spring.application.name=ecowash
server.port=9090

# Configuración de Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.jcczdginwnacwibtoejm
spring.datasource.password=BTr9p3xgY1g21G7w
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración de Thymeleaf
spring.thymeleaf.cache=false
# ==========================================
# BLINDAJE DE CONEXIONES HIKARICP
# ==========================================
# 1. Reduce el tamaño máximo para no asfixiar a PostgreSQL (5 es más que suficiente para desarrollo)
spring.datasource.hikari.maximum-pool-size=5

# 2. Permite que el servidor reduzca las conexiones a 1 si no hay tráfico
spring.datasource.hikari.minimum-idle=1

# 3. Si la base de datos no responde, espera 15 segundos antes de lanzar Error 500
spring.datasource.hikari.connection-timeout=15000

# 4. Destruye conexiones inactivas después de 30 segundos para que PostgreSQL no las mate primero
spring.datasource.hikari.idle-timeout=30000

# 5. Tiempo máximo de vida de una conexión (10 minutos), obliga a renovarlas constantemente
spring.datasource.hikari.max-lifetime=600000

# 6. Comprueba silenciosamente que el "cable" funcione antes de enviar una consulta real
spring.datasource.hikari.keepalive-time=40000