spring.application.name=ecowash
server.port=9090

# Configuración de Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.jcczdginwnacwibtoejm
spring.datasource.password=BTr9p3xgY1g21G7w
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración de Thymeleaf
spring.thymeleaf.cache=false
